name: tapl
version: '0.0.0'
author: Shinya Yamaguchi
github: waddlaw/TAPL

dependencies:
- base
- containers
- hashable
- QuickCheck
- unordered-containers

library:
  source-dirs: src

tests:
  test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - tapl
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
  # docktest:
  #   main: doctests.hs
  #   dependencies:
  #   - tapl

benchmarks:
  term:
    main: bench/Main.hs
    dependencies:
    - tapl
    - gauge

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs