name: tapl
version: 0.0.0
author: Shinya Yamaguchi
github: waddlaw/TAPL
dependencies:
  - base
  - containers
  - hashable
  - prettyprinter
  - QuickCheck
  - text
  - transformers
  - trifecta
  - unordered-containers
when:
  - condition: impl(ghc == 8.2.2)
    dependencies:
      - set-monad
library:
  source-dirs: src
  when:
    - condition: impl(ghc == 8.2.2)
      other-modules:
        - Term.MonadSet
executables:
  proofb:
    main: app/ProofB.hs
    dependencies:
      - tapl
      - haskeline
  nb:
    main: app/NB.hs
    dependencies:
      - tapl
      - haskeline
tests:
  test:
    main: Driver.hs
    source-dirs: test
    dependencies:
      - tapl
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
benchmarks:
  gauge:
    main: bench/Gauge.hs
    dependencies:
      - tapl
      - gauge
  criterion:
    main: bench/Criterion.hs
    dependencies:
      - tapl
      - criterion
ghc-options:
  - '-Wall'
  - '-Wcompat'
  - '-Wincomplete-uni-patterns'
  - '-Wincomplete-record-updates'
  - '-Wnoncanonical-monad-instances'
  - '-Wredundant-constraints'
  - '-Wtabs'
