name: tapl
version: '0.0.0'
author: Shinya Yamaguchi
github: waddlaw/TAPL

dependencies:
- base
- containers
- hashable
- prettyprinter
- QuickCheck
- set-monad
- transformers
- trifecta
- unordered-containers

library:
  source-dirs: src

executables:
  proofb:
    main: app/ProofB.hs
    dependencies:
    - tapl
    - haskeline

tests:
  test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - tapl
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
  # docktest:
  #   main: doctests.hs
  #   dependencies:
  #   - tapl

benchmarks:
  gauge:
    main: bench/Gauge.hs
    dependencies:
    - tapl
    - gauge
  criterion:
    main: bench/Criterion.hs
    dependencies:
    - tapl
    - criterion

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs